### ISSUE TITLE
Problem running npm run test on this project

### ISSUE THREAD

**Issue by MJBurge56** [Tallyb/cucumber-playwright#28]
I tried out your repo and I think I have it all setup correctly, but when I run _npm run test_ I get the following error:

C:\QA\PlayWright\cucumber-playwright-master\src\steps\general.steps.ts:6
    await page?.screenshot({ path: `screenshots/${name}.png` });
               ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (C:\QA\PlayWright\cucumber-playwright-master\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\QA\PlayWright\cucumber-playwright-master\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at supportCodePaths.forEach (C:\QA\PlayWright\cucumber-playwright-master\node_modules\@cucumber\cucumber\src\cli\index.ts:150:44)
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\QA\PlayWright\cucumber-playwright-master\node_modules\@cucumber\cucumber\src\cli\index.ts:150:22)
    at Cli.run (C:\QA\PlayWright\cucumber-playwright-master\node_modules\@cucumber\cucumber\src\cli\index.ts:169:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cucumber-playwright@1.0.0 test: `cucumber-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cucumber-playwright@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mburge\AppData\Roaming\npm-cache\_logs\2021-02-25T13_47_54_448Z-debug.log

**Comment by Tallyb** [comment]
I believe it is a windows issue. can you try the fix I pushed?

**Comment by MJBurge56** [comment]
Still getting the same error. I've noticed to get it this far I had to manually install a bunch of modules, what is the module used for the screenshot? I will try to install it manually.

**Comment by Tallyb** [comment]
That is weird. All should be included. It is built-in in playwright.

**Comment by Tallyb** [comment]
can you remove node_modules, run npm install and post the errors?

**Comment by MJBurge56** [comment]
Hi Tally,

I was finally able to get it up and running. Feel free to close the issue.

**Comment by cgnuechtel** [comment]
Thanks for this great repo!

Today I had the same issue under Windows. Just changed `tsconfig.json` to:

```json
"target": "es2018"
```

And it works!
